from django.urls import path

from vault.views import (
    accounts,
    collections,
    games,
    gamers,
    home,
    library,
    reference,
    comments,
)

urlpatterns = [
    path("", home.index, name="index"),
    path("register/", accounts.RegisterView.as_view(), name="register"),
    path(
        "register/done/",
        accounts.ActivationSentView.as_view(),
        name="activation-sent",
    ),
    path(
        "activate/<uidb64>/<token>/",
        accounts.activate,
        name="activate",
    ),
    path(
        "demo-login/<str:role>/",
        accounts.demo_login,
        name="demo-login",
    ),
    # Reference data
    path(
        "genres/",
        reference.GenreListView.as_view(),
        name="genre-list",
    ),
    path(
        "genres/create/",
        reference.GenreCreateView.as_view(),
        name="genre-create",
    ),
    path(
        "genres/<int:pk>/update/",
        reference.GenreUpdateView.as_view(),
        name="genre-update",
    ),
    path(
        "genres/<int:pk>/delete/",
        reference.GenreDeleteView.as_view(),
        name="genre-delete",
    ),
    path(
        "platforms/",
        reference.PlatformListView.as_view(),
        name="platform-list",
    ),
    path(
        "platforms/create/",
        reference.PlatformCreateView.as_view(),
        name="platform-create",
    ),
    path(
        "platforms/<int:pk>/update/",
        reference.PlatformUpdateView.as_view(),
        name="platform-update",
    ),
    path(
        "platforms/<int:pk>/delete/",
        reference.PlatformDeleteView.as_view(),
        name="platform-delete",
    ),
    path(
        "developers/",
        reference.DeveloperListView.as_view(),
        name="developer-list",
    ),
    path(
        "developers/create/",
        reference.DeveloperCreateView.as_view(),
        name="developer-create",
    ),
    path(
        "developers/<int:pk>/update/",
        reference.DeveloperUpdateView.as_view(),
        name="developer-update",
    ),
    path(
        "developers/<int:pk>/delete/",
        reference.DeveloperDeleteView.as_view(),
        name="developer-delete",
    ),
    # Games
    path("games/", games.GameListView.as_view(), name="game-list"),
    path(
        "games/create/",
        games.GameCreateView.as_view(),
        name="game-create",
    ),
    path(
        "games/<int:pk>/",
        games.GameDetailView.as_view(),
        name="game-detail",
    ),
    path(
        "games/<int:pk>/update/",
        games.GameUpdateView.as_view(),
        name="game-update",
    ),
    path(
        "games/<int:pk>/delete/",
        games.GameDeleteView.as_view(),
        name="game-delete",
    ),
    # Library
    path(
        "library/",
        library.LibraryEntryListView.as_view(),
        name="library-list",
    ),
    path(
        "games/<int:game_pk>/library/add/",
        library.LibraryEntryCreateView.as_view(),
        name="library-create",
    ),
    path(
        "library/<int:pk>/update/",
        library.LibraryEntryUpdateView.as_view(),
        name="library-update",
    ),
    path(
        "library/<int:pk>/delete/",
        library.LibraryEntryDeleteView.as_view(),
        name="library-delete",
    ),
    # Collections
    path(
        "collections/",
        collections.CollectionListView.as_view(),
        name="collection-list",
    ),
    path(
        "collections/create/",
        collections.CollectionCreateView.as_view(),
        name="collection-create",
    ),
    path(
        "collections/<int:pk>/",
        collections.CollectionDetailView.as_view(),
        name="collection-detail",
    ),
    path(
        "collections/<int:pk>/update/",
        collections.CollectionUpdateView.as_view(),
        name="collection-update",
    ),
    path(
        "collections/<int:pk>/delete/",
        collections.CollectionDeleteView.as_view(),
        name="collection-delete",
    ),
    path(
        "collections/<int:pk>/games/add/",
        collections.collection_add_game,
        name="collection-add-game",
    ),
    path(
        "collections/<int:pk>/games/<int:game_pk>/remove/",
        collections.collection_remove_game,
        name="collection-remove-game",
    ),
    # Gamers
    path("gamers/", gamers.GamerListView.as_view(), name="gamer-list"),
    path(
        "gamers/<int:pk>/",
        gamers.GamerDetailView.as_view(),
        name="gamer-detail",
    ),
    path(
        "gamers/<int:pk>/update/",
        gamers.GamerUpdateView.as_view(),
        name="gamer-update",
    ),
    path(
        "games/<int:pk>/comments/add/",
        comments.game_comment_add,
        name="game-comment-add",
    ),
    path(
        "collections/<int:pk>/comments/add/",
        comments.collection_comment_add,
        name="collection-comment-add",
    ),
    path(
        "comments/<int:pk>/delete/",
        comments.comment_delete,
        name="comment-delete",
    ),
]

app_name = "vault"
