# Generated by Django 6.1.1 on 2026-10-01 18:09

import django.db.models.deletion
import vault.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vault", "0002_genre_platform_developer"),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "release_year",
                    models.PositiveSmallIntegerField(
                        validators=[vault.validators.validate_release_year]
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("cover_url", models.URLField(blank=True)),
                (
                    "developer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="games",
                        to="vault.developer",
                    ),
                ),
                (
                    "genres",
                    models.ManyToManyField(
                        related_name="games", to="vault.genre"
                    ),
                ),
                (
                    "platforms",
                    models.ManyToManyField(
                        related_name="games", to="vault.platform"
                    ),
                ),
            ],
            options={
                "ordering": ["-release_year", "title"],
            },
        ),
    ]
