# Generated by Django 6.1.1 on 2026-10-01 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vault", "0003_game"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamer",
            name="favorite_genre",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fans",
                to="vault.genre",
            ),
        ),
    ]
