# Generated by Django 6.1.1 on 2026-10-01 18:58

import django.db.models.deletion
import vault.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vault", "0004_gamer_favorite_genre"),
    ]

    operations = [
        migrations.CreateModel(
            name="LibraryEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("playing", "Playing"),
                            ("completed", "Completed"),
                            ("dropped", "Dropped"),
                        ],
                        default="planned",
                        max_length=10,
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[vault.validators.validate_rating],
                    ),
                ),
                ("hours_played", models.PositiveIntegerField(default=0)),
                ("started_at", models.DateField(blank=True, null=True)),
                ("finished_at", models.DateField(blank=True, null=True)),
                ("note", models.TextField(blank=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="library_entries",
                        to="vault.game",
                    ),
                ),
                (
                    "gamer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="library_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "platform",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="library_entries",
                        to="vault.platform",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "library entries",
                "ordering": ["-rating", "hours_played"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("gamer", "game"),
                        name="unique_gamer_game_entry",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("rating__isnull", True),
                            models.Q(("rating__gte", 1), ("rating__lte", 10)),
                            _connector="OR",
                        ),
                        name="rating_within_bounds",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("started_at__isnull", True),
                            ("finished_at__isnull", True),
                            ("finished_at__gte", models.F("started_at")),
                            _connector="OR",
                        ),
                        name="finished_not_before_started",
                    ),
                ],
            },
        ),
    ]
