# Generated by Django 6.1.1 on 2026-10-05 00:21

import vault.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vault", "0006_collection"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="cover",
            field=models.ImageField(
                blank=True,
                upload_to="covers/",
                validators=[vault.validators.validate_image_size],
            ),
        ),
    ]
