# Generated by Django 6.1.1 on 2026-10-07 22:44

import vault.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vault", "0008_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamer",
            name="avatar",
            field=models.ImageField(
                blank=True,
                upload_to="avatars/",
                validators=[vault.validators.validate_image_size],
            ),
        ),
        migrations.AddField(
            model_name="gamer",
            name="avatar_url",
            field=models.URLField(blank=True),
        ),
    ]
