"""Extra demo activity for seed_data: library entries, collections, comments.

Entries here are short: no dates, just status, rating, hours and platform.
"""

from vault.management.commands._catalog import (
    MAC,
    PC,
    PS4,
    PS5,
    SWITCH,
    XB1,
    XBOX,
)
from vault.models import LibraryEntry

Status = LibraryEntry.Status

# username, game title, status, rating, hours, platform, note
EXTRA_ENTRIES = [
    # alex: story-driven RPGs and adventures
    ("alex", "Baldur's Gate 3", Status.COMPLETED, 10, 160, PC, "Perfect."),
    ("alex", "Disco Elysium", Status.COMPLETED, 10, 35, PC, "Unique."),
    ("alex", "Red Dead Redemption 2", Status.COMPLETED, 10, 90, PC, ""),
    ("alex", "Kingdom Come: Deliverance", Status.PLAYING, 8, 45, PC, ""),
    ("alex", "The Last of Us Part II", Status.COMPLETED, 9, 28, PS5, ""),
    ("alex", "Final Fantasy VII Remake", Status.PLANNED, None, 0, PS5, ""),
    ("alex", "Alan Wake 2", Status.DROPPED, 6, 4, PC, "Too scary at night."),
    (
        "alex",
        "The Elder Scrolls V: Skyrim",
        Status.COMPLETED,
        9,
        210,
        PC,
        "Arrow in the knee.",
    ),
    ("alex", "Death Stranding", Status.PLAYING, 7, 20, PC, ""),
    # maria: Nintendo, indie and roguelikes
    (
        "maria",
        "Hollow Knight",
        Status.COMPLETED,
        10,
        55,
        SWITCH,
        "Masterpiece.",
    ),
    ("maria", "Celeste", Status.COMPLETED, 9, 14, SWITCH, ""),
    (
        "maria",
        "Stardew Valley",
        Status.PLAYING,
        10,
        300,
        SWITCH,
        "One more day.",
    ),
    ("maria", "Dead Cells", Status.COMPLETED, 9, 60, SWITCH, ""),
    ("maria", "Slay the Spire", Status.PLAYING, 9, 85, PC, ""),
    (
        "maria",
        "Animal Crossing: New Horizons",
        Status.PLAYING,
        8,
        250,
        SWITCH,
        "",
    ),
    ("maria", "Mario Kart 8 Deluxe", Status.COMPLETED, 9, 120, SWITCH, ""),
    (
        "maria",
        "The Legend of Zelda: Tears of the Kingdom",
        Status.PLAYING,
        10,
        140,
        SWITCH,
        "Building is addictive.",
    ),
    ("maria", "Ori and the Blind Forest", Status.PLANNED, None, 0, SWITCH, ""),
    ("maria", "Cuphead", Status.DROPPED, 5, 6, SWITCH, "Too hard for me."),
    (
        "maria",
        "It Takes Two",
        Status.COMPLETED,
        9,
        14,
        PC,
        "Played with Taras.",
    ),
    # taras: hard games, shooters, Ukrainian studios
    ("taras", "Bloodborne", Status.COMPLETED, 10, 70, PS4, ""),
    (
        "taras",
        "Armored Core VI: Fires of Rubicon",
        Status.COMPLETED,
        8,
        40,
        PC,
        "",
    ),
    (
        "taras",
        "S.T.A.L.K.E.R. 2: Heart of Chornobyl",
        Status.PLAYING,
        8,
        60,
        PC,
        "",
    ),
    ("taras", "Metro Exodus", Status.COMPLETED, 9, 30, PC, ""),
    ("taras", "Doom Eternal", Status.COMPLETED, 9, 25, PC, ""),
    (
        "taras",
        "Counter-Strike 2",
        Status.PLAYING,
        8,
        900,
        PC,
        "Just one more.",
    ),
    ("taras", "Left 4 Dead 2", Status.COMPLETED, 9, 80, PC, ""),
    ("taras", "Resident Evil 4", Status.COMPLETED, 9, 18, PS5, ""),
    ("taras", "Devil May Cry 5", Status.PLANNED, None, 0, PC, ""),
    ("taras", "Hollow Knight", Status.DROPPED, 6, 12, PC, "Got lost."),
    # demo_admin
    ("demo_admin", "God of War", Status.COMPLETED, 10, 38, PS4, ""),
    ("demo_admin", "God of War Ragnarök", Status.PLAYING, 9, 30, PS5, ""),
    ("demo_admin", "Marvel's Spider-Man", Status.COMPLETED, 9, 25, PS4, ""),
    ("demo_admin", "Ghost of Tsushima", Status.COMPLETED, 9, 45, PS5, ""),
    ("demo_admin", "Horizon Zero Dawn", Status.COMPLETED, 8, 50, PS4, ""),
    ("demo_admin", "Grand Theft Auto V", Status.COMPLETED, 9, 100, PC, ""),
    ("demo_admin", "Forza Horizon 5", Status.PLANNED, None, 0, XBOX, ""),
    # demo_moderator
    ("demo_moderator", "Minecraft", Status.PLAYING, 10, 400, PC, ""),
    ("demo_moderator", "Terraria", Status.COMPLETED, 9, 150, PC, ""),
    ("demo_moderator", "Subnautica", Status.COMPLETED, 9, 35, PC, ""),
    ("demo_moderator", "Outer Wilds", Status.COMPLETED, 10, 22, PC, ""),
    ("demo_moderator", "Inside", Status.COMPLETED, 9, 4, PC, ""),
    ("demo_moderator", "Cities: Skylines", Status.PLAYING, 8, 120, PC, ""),
    (
        "demo_moderator",
        "Sid Meier's Civilization VI",
        Status.PLAYING,
        9,
        200,
        MAC,
        "",
    ),
    ("demo_moderator", "XCOM 2", Status.DROPPED, 6, 10, PC, "Missed 95%."),
    ("demo_moderator", "Persona 5 Royal", Status.PLANNED, None, 0, PC, ""),
    (
        "demo_moderator",
        "Divinity: Original Sin 2",
        Status.PLANNED,
        None,
        0,
        PC,
        "",
    ),
    ("demo_moderator", "Fallout 4", Status.DROPPED, 5, 15, XB1, ""),
    (
        "demo_moderator",
        "Monster Hunter: World",
        Status.PLAYING,
        8,
        70,
        PS4,
        "",
    ),
    ("demo_moderator", "Street Fighter 6", Status.PLAYING, 7, 20, PS5, ""),
    ("demo_moderator", "Splatoon 3", Status.COMPLETED, 8, 40, SWITCH, ""),
    (
        "demo_moderator",
        "Super Smash Bros. Ultimate",
        Status.COMPLETED,
        9,
        90,
        SWITCH,
        "",
    ),
    ("demo_moderator", "Control", Status.COMPLETED, 8, 18, PC, ""),
]

# owner, title, description, game titles
EXTRA_COLLECTIONS = [
    (
        "alex",
        "Ukrainian studios",
        "Games made in Ukraine.",
        ["S.T.A.L.K.E.R. 2: Heart of Chornobyl", "Metro Exodus"],
    ),
    (
        "alex",
        "Open worlds worth the hours",
        "Huge maps, even bigger stories.",
        [
            "Red Dead Redemption 2",
            "The Elder Scrolls V: Skyrim",
            "Ghost of Tsushima",
            "Horizon Zero Dawn",
            "Grand Theft Auto V",
        ],
    ),
    (
        "maria",
        "Indie gems",
        "Small teams, big hearts.",
        [
            "Hollow Knight",
            "Celeste",
            "Stardew Valley",
            "Dead Cells",
            "Outer Wilds",
            "Inside",
        ],
    ),
    (
        "maria",
        "Couch co-op",
        "Best played with a friend on the sofa.",
        ["It Takes Two", "Mario Kart 8 Deluxe", "Cuphead", "Splatoon 3"],
    ),
    (
        "taras",
        "Horror nights",
        "Turn the lights off.",
        [
            "Resident Evil 4",
            "Alan Wake 2",
            "Bloodborne",
            "Left 4 Dead 2",
            "Metro Exodus",
        ],
    ),
    (
        "demo_admin",
        "PlayStation exclusives",
        "The reasons to own a PlayStation.",
        [
            "God of War",
            "God of War Ragnarök",
            "Marvel's Spider-Man",
            "The Last of Us Part II",
            "Ghost of Tsushima",
        ],
    ),
    (
        "demo_moderator",
        "Sandbox and survival",
        "Build, craft, survive.",
        ["Minecraft", "Terraria", "Subnautica", "Stardew Valley"],
    ),
    (
        "demo_moderator",
        "Strategy corner",
        "For those who like to think.",
        [
            "Sid Meier's Civilization VI",
            "XCOM 2",
            "Cities: Skylines",
            "Slay the Spire",
            "Baldur's Gate 3",
        ],
    ),
]

EXTRA_GAME_COMMENTS = [
    ("alex", "Baldur's Gate 3", "Every companion is memorable."),
    ("taras", "Baldur's Gate 3", "I need a free weekend for this one."),
    ("maria", "Hollow Knight", "The music alone is worth it."),
    ("taras", "Hollow Knight", "I got lost in the Fungal Wastes again."),
    ("alex", "Red Dead Redemption 2", "Arthur's story hit me hard."),
    ("taras", "Bloodborne", "Still the best FromSoftware game for me."),
    ("maria", "Stardew Valley", "300 hours and I still plant parsnips."),
    ("demo_moderator", "Outer Wilds", "Go in blind, do not read anything."),
    (
        "alex",
        "S.T.A.L.K.E.R. 2: Heart of Chornobyl",
        "The atmosphere is great.",
    ),
    ("maria", "It Takes Two", "Taras and I did it in one weekend."),
    ("demo_admin", "God of War", "The one-shot camera is a masterpiece."),
    ("taras", "Counter-Strike 2", "Rank is a lie, aim is real."),
]

EXTRA_COLLECTION_COMMENTS = [
    ("taras", "Indie gems", "Outer Wilds deserves the first place."),
    ("alex", "Couch co-op", "Add Overcooked next time!"),
    ("maria", "Horror nights", "I am not brave enough for this list."),
    ("demo_moderator", "Ukrainian studios", "Proud of this list."),
]
