"""Catalog data for seed_data: genres, platforms, developers and games."""

PC = "PC"
PS5 = "PlayStation 5"
PS4 = "PlayStation 4"
XBOX = "Xbox Series X"
XB1 = "Xbox One"
SWITCH = "Nintendo Switch"
MAC = "macOS"
MOBILE = "Mobile"

GENRES = [
    "RPG",
    "Action",
    "Adventure",
    "Puzzle",
    "Roguelike",
    "Platformer",
    "Shooter",
    "Strategy",
    "Simulation",
    "Horror",
    "Survival",
    "Racing",
    "Fighting",
    "Metroidvania",
    "JRPG",
    "Indie",
]

PLATFORMS = [PC, PS5, XBOX, SWITCH, PS4, XB1, MAC, MOBILE]

DEVELOPERS = [
    ("CD Projekt Red", "Poland"),
    ("FromSoftware", "Japan"),
    ("Valve", "USA"),
    ("Supergiant Games", "USA"),
    ("Nintendo", "Japan"),
    ("Rockstar Games", "USA"),
    ("Naughty Dog", "USA"),
    ("Santa Monica Studio", "USA"),
    ("Insomniac Games", "USA"),
    ("Sucker Punch Productions", "USA"),
    ("Guerrilla Games", "Netherlands"),
    ("Bethesda Game Studios", "USA"),
    ("id Software", "USA"),
    ("Larian Studios", "Belgium"),
    ("Capcom", "Japan"),
    ("Square Enix", "Japan"),
    ("Atlus", "Japan"),
    ("Kojima Productions", "Japan"),
    ("Remedy Entertainment", "Finland"),
    ("GSC Game World", "Ukraine"),
    ("4A Games", "Ukraine"),
    ("Warhorse Studios", "Czech Republic"),
    ("Firaxis Games", "USA"),
    ("Colossal Order", "Finland"),
    ("Playground Games", "UK"),
    ("Team Cherry", "Australia"),
    ("Maddy Makes Games", "Canada"),
    ("ConcernedApe", "USA"),
    ("Re-Logic", "USA"),
    ("Mojang Studios", "Sweden"),
    ("Playdead", "Denmark"),
    ("ZA/UM", "UK"),
    ("Motion Twin", "France"),
    ("Mega Crit", "USA"),
    ("Unknown Worlds Entertainment", "USA"),
    ("Mobius Digital", "USA"),
    ("Moon Studios", "Austria"),
    ("Studio MDHR", "Canada"),
    ("Hazelight Studios", "Sweden"),
]


STEAM_COVER_URL = (
    "https://cdn.cloudflare.steamstatic.com/steam/apps/{}/header.jpg"
)

# Steam app ids of the games that are sold on Steam. Games from other
# stores (Nintendo, Minecraft, Bloodborne) have no cover and show a
# placeholder.
# Check them with `python check_steam_covers.py` (needs internet).
STEAM_APP_IDS = {
    "The Witcher 3: Wild Hunt": 292030,
    "Cyberpunk 2077": 1091500,
    "Elden Ring": 1245620,
    "Dark Souls III": 374320,
    "Sekiro: Shadows Die Twice": 814380,
    "Portal 2": 620,
    "Half-Life 2": 220,
    "Half-Life: Alyx": 546560,
    "Hades": 1145360,
    "Red Dead Redemption 2": 1174180,
    "Grand Theft Auto V": 271590,
    "The Last of Us Part II": 2531310,
    "God of War": 1593500,
    "God of War Ragnarök": 2322010,
    "Marvel's Spider-Man": 1817070,
    "Ghost of Tsushima": 2215430,
    "Horizon Zero Dawn": 1151640,
    "Death Stranding": 1190460,
    "The Elder Scrolls V: Skyrim": 489830,
    "Fallout 4": 377160,
    "Baldur's Gate 3": 1086940,
    "Divinity: Original Sin 2": 435150,
    "Kingdom Come: Deliverance": 379430,
    "Disco Elysium": 632470,
    "Sid Meier's Civilization VI": 289070,
    "XCOM 2": 268500,
    "Cities: Skylines": 255710,
    "Final Fantasy VII Remake": 1462040,
    "Persona 5 Royal": 1687950,
    "Resident Evil 4": 2050650,
    "Monster Hunter: World": 582010,
    "Devil May Cry 5": 601150,
    "Street Fighter 6": 1364780,
    "Armored Core VI: Fires of Rubicon": 1888160,
    "Doom Eternal": 782330,
    "Left 4 Dead 2": 550,
    "Counter-Strike 2": 730,
    "Alan Wake 2": 1282100,
    "Control": 870780,
    "S.T.A.L.K.E.R. 2: Heart of Chornobyl": 1643320,
    "Metro Exodus": 412020,
    "Terraria": 105600,
    "Stardew Valley": 413150,
    "Subnautica": 264710,
    "Hollow Knight": 367520,
    "Celeste": 504230,
    "Dead Cells": 588650,
    "Slay the Spire": 646570,
    "Ori and the Blind Forest": 387290,
    "Cuphead": 268910,
    "Inside": 304430,
    "Outer Wilds": 753640,
    "It Takes Two": 1426210,
    "Forza Horizon 5": 1551360,
}


def cover_url(title):
    app_id = STEAM_APP_IDS.get(title)
    return STEAM_COVER_URL.format(app_id) if app_id else ""


def game(title, year, developer, genres, platforms, description):
    return {
        "title": title,
        "cover_url": cover_url(title),
        "release_year": year,
        "developer": developer,
        "genres": genres,
        "platforms": platforms,
        "description": description,
    }


GAMES = [
    game(
        "The Witcher 3: Wild Hunt",
        2015,
        "CD Projekt Red",
        ["RPG", "Action"],
        [PC, PS5, XBOX, SWITCH, PS4, XB1],
        "Open-world RPG about a monster hunter.",
    ),
    game(
        "Cyberpunk 2077",
        2020,
        "CD Projekt Red",
        ["RPG", "Action"],
        [PC, PS5, XBOX, PS4, XB1],
        "Sci-fi RPG set in Night City.",
    ),
    game(
        "Elden Ring",
        2022,
        "FromSoftware",
        ["RPG", "Action", "Adventure"],
        [PC, PS5, XBOX, PS4, XB1],
        "Open-world action RPG in the Lands Between.",
    ),
    game(
        "Dark Souls III",
        2016,
        "FromSoftware",
        ["RPG", "Action"],
        [PC, PS5, XBOX, PS4, XB1],
        "Punishing action RPG about linking the fire.",
    ),
    game(
        "Sekiro: Shadows Die Twice",
        2019,
        "FromSoftware",
        ["Action", "Adventure"],
        [PC, PS5, XBOX, PS4, XB1],
        "Shinobi action game in feudal Japan.",
    ),
    game(
        "Portal 2",
        2011,
        "Valve",
        ["Puzzle", "Adventure"],
        [PC, SWITCH],
        "Physics puzzles with portals and GLaDOS.",
    ),
    game(
        "Half-Life 2",
        2004,
        "Valve",
        ["Action", "Adventure"],
        [PC],
        "Classic first-person shooter with a crowbar.",
    ),
    game(
        "Half-Life: Alyx",
        2020,
        "Valve",
        ["Action", "Adventure"],
        [PC],
        "VR prequel in the Half-Life universe.",
    ),
    game(
        "Hades",
        2020,
        "Supergiant Games",
        ["Roguelike", "Action"],
        [PC, SWITCH, PS5, XBOX],
        "Escape the Underworld, again and again.",
    ),
    game(
        "The Legend of Zelda: Breath of the Wild",
        2017,
        "Nintendo",
        ["Adventure", "Action"],
        [SWITCH],
        "Explore Hyrule however you like.",
    ),
    game(
        "Super Mario Odyssey",
        2017,
        "Nintendo",
        ["Platformer", "Adventure"],
        [SWITCH],
        "Mario travels the world with a living hat.",
    ),
    game(
        "Metroid Dread",
        2021,
        "Nintendo",
        ["Platformer", "Action"],
        [SWITCH],
        "Samus is hunted by E.M.M.I. robots.",
    ),
    # Rockstar, Sony and other big action-adventures
    game(
        "Red Dead Redemption 2",
        2018,
        "Rockstar Games",
        ["Action", "Adventure"],
        [PC, PS4, XB1],
        "Outlaw epic in the dying Wild West.",
    ),
    game(
        "Grand Theft Auto V",
        2013,
        "Rockstar Games",
        ["Action", "Adventure"],
        [PC, PS4, XB1, PS5, XBOX],
        "Three criminals, one heist-filled Los Santos.",
    ),
    game(
        "The Last of Us Part II",
        2020,
        "Naughty Dog",
        ["Action", "Adventure", "Survival"],
        [PS4, PS5],
        "A brutal story of revenge in a post-pandemic America.",
    ),
    game(
        "God of War",
        2018,
        "Santa Monica Studio",
        ["Action", "Adventure"],
        [PS4, PC],
        "Kratos and his son travel through Norse realms.",
    ),
    game(
        "God of War Ragnarök",
        2022,
        "Santa Monica Studio",
        ["Action", "Adventure"],
        [PS4, PS5, PC],
        "The Fimbulwinter ends in a war of the gods.",
    ),
    game(
        "Marvel's Spider-Man",
        2018,
        "Insomniac Games",
        ["Action", "Adventure"],
        [PS4, PC],
        "Swing across Manhattan as an experienced Peter Parker.",
    ),
    game(
        "Ghost of Tsushima",
        2020,
        "Sucker Punch Productions",
        ["Action", "Adventure"],
        [PS4, PS5, PC],
        "A samurai defends his island from the Mongol invasion.",
    ),
    game(
        "Horizon Zero Dawn",
        2017,
        "Guerrilla Games",
        ["Action", "RPG", "Adventure"],
        [PS4, PC, PS5],
        "Hunt robotic dinosaurs in a post-apocalyptic world.",
    ),
    game(
        "Death Stranding",
        2019,
        "Kojima Productions",
        ["Action", "Adventure"],
        [PS4, PC, PS5],
        "Reconnect a broken America, one delivery at a time.",
    ),
    # Western RPGs and strategy
    game(
        "The Elder Scrolls V: Skyrim",
        2011,
        "Bethesda Game Studios",
        ["RPG", "Adventure"],
        [PC, PS4, XB1, SWITCH, PS5, XBOX],
        "Dragons return to the land of the Nords.",
    ),
    game(
        "Fallout 4",
        2015,
        "Bethesda Game Studios",
        ["RPG", "Action"],
        [PC, PS4, XB1],
        "Rebuild the Commonwealth after the nuclear war.",
    ),
    game(
        "Baldur's Gate 3",
        2023,
        "Larian Studios",
        ["RPG", "Strategy"],
        [PC, PS5, XBOX, MAC],
        "Turn-based D&D adventure with unforgettable companions.",
    ),
    game(
        "Divinity: Original Sin 2",
        2017,
        "Larian Studios",
        ["RPG", "Strategy"],
        [PC, PS4, XB1, SWITCH, MAC],
        "Tactical RPG where almost everything can be set on fire.",
    ),
    game(
        "Kingdom Come: Deliverance",
        2018,
        "Warhorse Studios",
        ["RPG", "Adventure"],
        [PC, PS4, XB1],
        "Realistic medieval RPG set in Bohemia.",
    ),
    game(
        "Disco Elysium",
        2019,
        "ZA/UM",
        ["RPG", "Indie"],
        [PC, PS4, XB1, SWITCH, PS5, XBOX, MAC],
        "A detective RPG made of skills, thoughts and dialogue.",
    ),
    game(
        "Sid Meier's Civilization VI",
        2016,
        "Firaxis Games",
        ["Strategy"],
        [PC, SWITCH, PS4, XB1, MAC, MOBILE],
        "Build an empire to stand the test of time.",
    ),
    game(
        "XCOM 2",
        2016,
        "Firaxis Games",
        ["Strategy"],
        [PC, PS4, XB1, SWITCH, MAC],
        "Lead the resistance against alien occupation.",
    ),
    game(
        "Cities: Skylines",
        2015,
        "Colossal Order",
        ["Simulation", "Strategy"],
        [PC, PS4, XB1, SWITCH, MAC],
        "A modern city builder with realistic traffic.",
    ),
    # Japanese studios
    game(
        "Final Fantasy VII Remake",
        2020,
        "Square Enix",
        ["JRPG", "RPG", "Action"],
        [PS4, PS5, PC],
        "A reimagining of the Midgar chapter of Final Fantasy VII.",
    ),
    game(
        "Persona 5 Royal",
        2019,
        "Atlus",
        ["JRPG", "RPG"],
        [PS4, PS5, PC, SWITCH, XB1, XBOX],
        "Phantom Thieves steal hearts in modern Tokyo.",
    ),
    game(
        "Resident Evil 4",
        2023,
        "Capcom",
        ["Horror", "Action", "Shooter"],
        [PC, PS5, XBOX, PS4],
        "Remake of the survival horror classic.",
    ),
    game(
        "Monster Hunter: World",
        2018,
        "Capcom",
        ["Action", "RPG"],
        [PC, PS4, XB1],
        "Hunt giant monsters in the New World.",
    ),
    game(
        "Devil May Cry 5",
        2019,
        "Capcom",
        ["Action"],
        [PC, PS4, XB1, PS5, XBOX],
        "Stylish demon slaying with three playable heroes.",
    ),
    game(
        "Street Fighter 6",
        2023,
        "Capcom",
        ["Fighting"],
        [PC, PS4, PS5, XBOX],
        "The fighting-game classic with a single-player World Tour.",
    ),
    game(
        "Bloodborne",
        2015,
        "FromSoftware",
        ["Action", "RPG", "Horror"],
        [PS4],
        "Gothic nightmare in the city of Yharnam.",
    ),
    game(
        "Armored Core VI: Fires of Rubicon",
        2023,
        "FromSoftware",
        ["Action"],
        [PC, PS4, PS5, XB1, XBOX],
        "Fast mech combat on the planet Rubicon.",
    ),
    # Shooters and horror
    game(
        "Doom Eternal",
        2020,
        "id Software",
        ["Shooter", "Action"],
        [PC, PS4, XB1, SWITCH, PS5, XBOX],
        "Rip and tear through the armies of Hell.",
    ),
    game(
        "Left 4 Dead 2",
        2009,
        "Valve",
        ["Shooter", "Action", "Horror"],
        [PC, MAC],
        "Four survivors fight through hordes of infected.",
    ),
    game(
        "Counter-Strike 2",
        2023,
        "Valve",
        ["Shooter"],
        [PC],
        "The legendary tactical shooter on a new engine.",
    ),
    game(
        "Alan Wake 2",
        2023,
        "Remedy Entertainment",
        ["Horror", "Adventure"],
        [PC, PS5, XBOX],
        "A writer trapped in a nightmare, an agent hunting a cult.",
    ),
    game(
        "Control",
        2019,
        "Remedy Entertainment",
        ["Action", "Adventure"],
        [PC, PS4, XB1, PS5, XBOX],
        "Explore the shifting Oldest House as Jesse Faden.",
    ),
    game(
        "S.T.A.L.K.E.R. 2: Heart of Chornobyl",
        2024,
        "GSC Game World",
        ["Shooter", "Survival", "Horror"],
        [PC, XBOX],
        "Survive in the open-world Zone of Exclusion.",
    ),
    game(
        "Metro Exodus",
        2019,
        "4A Games",
        ["Shooter", "Horror", "Adventure"],
        [PC, PS4, XB1, PS5, XBOX],
        "A train journey across post-apocalyptic Russia.",
    ),
    # Sandboxes, survival and simulation
    game(
        "Minecraft",
        2011,
        "Mojang Studios",
        ["Survival", "Adventure"],
        [PC, PS4, XB1, SWITCH, MOBILE, PS5, XBOX, MAC],
        "Mine, craft and build whatever you can imagine.",
    ),
    game(
        "Terraria",
        2011,
        "Re-Logic",
        ["Survival", "Adventure", "Indie"],
        [PC, PS4, XB1, SWITCH, MOBILE, MAC],
        "2D sandbox of digging, fighting and exploring.",
    ),
    game(
        "Stardew Valley",
        2016,
        "ConcernedApe",
        ["Simulation", "RPG", "Indie"],
        [PC, SWITCH, PS4, XB1, MOBILE, MAC],
        "Inherit a farm and start a new life in the valley.",
    ),
    game(
        "Subnautica",
        2018,
        "Unknown Worlds Entertainment",
        ["Survival", "Adventure"],
        [PC, PS4, XB1, SWITCH, PS5, XBOX, MAC],
        "Survive on an alien ocean planet.",
    ),
    # Indie and platformers
    game(
        "Hollow Knight",
        2017,
        "Team Cherry",
        ["Metroidvania", "Platformer", "Indie"],
        [PC, SWITCH, PS4, XB1, MAC],
        "Explore the ruined insect kingdom of Hallownest.",
    ),
    game(
        "Celeste",
        2018,
        "Maddy Makes Games",
        ["Platformer", "Indie"],
        [PC, SWITCH, PS4, XB1, MAC],
        "Climb a mountain in a tough but heartfelt platformer.",
    ),
    game(
        "Dead Cells",
        2018,
        "Motion Twin",
        ["Roguelike", "Metroidvania", "Indie"],
        [PC, SWITCH, PS4, XB1, MOBILE, MAC],
        "A roguelite action-platformer with a castle that changes.",
    ),
    game(
        "Slay the Spire",
        2019,
        "Mega Crit",
        ["Roguelike", "Strategy", "Indie"],
        [PC, SWITCH, PS4, XB1, MOBILE, MAC],
        "Climb the Spire by building a deck of cards.",
    ),
    game(
        "Ori and the Blind Forest",
        2015,
        "Moon Studios",
        ["Metroidvania", "Platformer", "Indie"],
        [PC, XB1, SWITCH],
        "A beautiful journey of a spirit guardian.",
    ),
    game(
        "Cuphead",
        2017,
        "Studio MDHR",
        ["Platformer", "Action", "Indie"],
        [PC, XB1, SWITCH, PS4, MAC],
        "Run-and-gun boss rush drawn in 1930s cartoon style.",
    ),
    game(
        "Inside",
        2016,
        "Playdead",
        ["Puzzle", "Platformer", "Indie"],
        [PC, PS4, XB1, SWITCH, MAC, MOBILE],
        "A dark, wordless puzzle-platformer.",
    ),
    game(
        "Outer Wilds",
        2019,
        "Mobius Digital",
        ["Adventure", "Puzzle", "Indie"],
        [PC, PS4, XB1, SWITCH, PS5, XBOX],
        "Explore a solar system stuck in a 22-minute time loop.",
    ),
    game(
        "It Takes Two",
        2021,
        "Hazelight Studios",
        ["Adventure", "Platformer", "Puzzle"],
        [PC, PS4, XB1, PS5, XBOX, SWITCH],
        "A co-op-only adventure about a couple turned into dolls.",
    ),
    # Racing and Nintendo
    game(
        "Forza Horizon 5",
        2021,
        "Playground Games",
        ["Racing"],
        [PC, XB1, XBOX],
        "Open-world racing festival in Mexico.",
    ),
    game(
        "Mario Kart 8 Deluxe",
        2017,
        "Nintendo",
        ["Racing"],
        [SWITCH],
        "The ultimate party racer with every track and item.",
    ),
    game(
        "Animal Crossing: New Horizons",
        2020,
        "Nintendo",
        ["Simulation"],
        [SWITCH],
        "Build a life and a community on a deserted island.",
    ),
    game(
        "Super Smash Bros. Ultimate",
        2018,
        "Nintendo",
        ["Fighting", "Platformer"],
        [SWITCH],
        "Every fighter in the series' history in one crossover.",
    ),
    game(
        "Splatoon 3",
        2022,
        "Nintendo",
        ["Shooter"],
        [SWITCH],
        "Colorful team-based ink shooter.",
    ),
    game(
        "The Legend of Zelda: Tears of the Kingdom",
        2023,
        "Nintendo",
        ["Adventure", "Action"],
        [SWITCH],
        "Explore the sky islands, the surface and the depths of Hyrule.",
    ),
]
